file_format: "1"
id: 4c
name: 4c
type: shield
url: https://github.com
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - 4c_left
  - 4c_right
layouts:
  - id: default_layout
    transform: keymap_transform_0 # Fixed: Points directly to your DTS transform node label
    kscan: kscan0
