# Uncomment the following line to enable the 4c OLED Display
CONFIG_ZMK_DISPLAY=y
# Enable ZMK Studio Runtime
CONFIG_ZMK_STUDIO=y

# Maintain RAM buffer stability for both Studio and LVGL
CONFIG_LV_Z_MEM_POOL_SIZE=8192

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
