#config/boards/shields/compression4c/zmk,matrix-transform.yaml
description: Matrix transform definition patch to allow key indexing bindings for ZMK Studio
compatible: "zmk,matrix-transform"
include: base.yaml
properties:
  "#key-cells":
    type: int
    const: 2
